### ISSUE TITLE
No loading indicator on initial load

### ISSUE THREAD

**Issue by paulcustance-al** [pop-os/cosmic-store#135]
When first launching the application there is no visual indicator to suggest it is loading or working, I'd initially thought it was broken but the icons did eventually appear, imagine this will be more prevalent on slower connections.

![cosmic-no-loading-indicator](https://github.com/user-attachments/assets/018c0446-f4e7-402a-8cb7-e680a7876c6a)

**Comment by WatchMkr** [comment]
Recent modifications should have made a loading indicator unnecessary.
