### ISSUE TITLE
Attempting to interact with "System Packages" fails. 

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-store#14]
With recent (0449d41b2ec7ac5e80ded693db8bb354b5b6a6e7) support for package updates, I was attempting to update the "System Packages", but was getting no response in application, and was seeing `[ERROR cosmic-store] failed to get appstream data for __SYSTEM__: failed to find info for __SYSTEM__` in the logs.

**Comment by jackpot51** [comment]
It is not implemented yet, it is a placeholder for updating regular packages. I'll be working on this soon.
