### ISSUE TITLE
[Enhancement] Separate Installed Apps from Available Apps in Cosmic App Store Search Results

### ISSUE THREAD

**Issue by iamkartiknayak** [pop-os/cosmic-store#145]
Currently, when a search is performed in the Cosmic app store, both installed apps and available apps in the store are displayed together in the search results no matter what tab is selected in left pane. This can make it difficult for users to distinguish between apps that are already installed and those that are available for installation.

Similar issue is mentioned here #109 

![Cosmic-Store-Search-Results-Enhancement](https://github.com/user-attachments/assets/2a95a658-f2e5-4ae9-9bc8-2459b10d5f6e)

**Comment by WatchMkr** [comment]
We'll track the request with https://github.com/pop-os/cosmic-store/issues/109
