### ISSUE TITLE
Application cards truncate names without indication.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-store#15]
While truncating long application names is inevitable, I wonder if truncated names should have some kind of indicator like an ellipses to signal that it isn't the full name. 

For one thing, I'm uncertain how this would interact with non-alphabetic languages, or even with languages with ligatures which are context dependent. But the inverse is that it is possible for things like version differences - Imagine that `Program With-Long-Name Version 1` and `Program With-Long-Name Version 2 ` both truncate to `Program With-Long-Name` - to become muddled. 

For example, in this screen shot, GIMP's name is truncated:
![screenshot-2024-03-13-19-23-30_inset](https://github.com/pop-os/cosmic-store/assets/98765732/9e4f2c1d-86fc-466f-8151-8645b8335cdc)

I don't know the correct course here, but did wish to raise the issue.

**Comment by XV-02** [comment]
That makes sense. Should I open an issue in cosmic-text for posterity?

**Comment by jackpot51** [comment]
Nah, it is a known issue.
