### ISSUE TITLE
Update status lost if a different tab is selected

### ISSUE THREAD

**Issue by lucamosca1** [pop-os/cosmic-store#152]
Pre requisite
Have several packages available to be updated, click update

Stesp to reproduce
During update, change tab, for example games, and then come back to updates tab

Actual result
Update status, with details about package and progress, is lost

Video in attachment
[CosmicUpdates.webm](https://github.com/user-attachments/assets/b15f8341-9263-4175-a028-a54dab7b20f9)

**Comment by jackpot51** [comment]
We will have a global status indicator at some point, #106

**Comment by lucamosca1** [comment]
Cool, in this case you can consider this topic closed.
