### ISSUE TITLE
The Explore view doesn't have a loading text, even when it takes a bit of time to show the applications at the startup

### ISSUE THREAD

**Issue by senntore** [pop-os/cosmic-store#154]
I have seen some videos where people thought the appstore was empty as they tried to click on all of the categories on the sidebar, after seeing nothing on the Explore page.
You could add loading text similar to the Updates page.
Of course this wouldn't be necessary if the Explore view shows the application instantly but that is not the case right now.

**Comment by WatchMkr** [comment]
We're satisfied that loading text is no longer necessary after recent optimizations.
