### ISSUE TITLE
Cannot manage deb packages.

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-store#16]
When I try to update any individual deb package, the update does not happen.

I tried this with Firefox. 

I click update, the authorization prompt appears and seems to accept the password, and then nothing happens. 

Store has access to a newer version of the package, as Firefox was on version 122, and after uninstalling and reinstalling Firefox through Store the version is 123.

**Comment by XV-02** [comment]
Somewhere between 9017bc9d137fa5b16af0a661bb5d6a0849a7e75e and df014ea82ae0465470f5d237bfe71d2c085d29a0 cosmic-store lost the ability to install deb packages. 

At 9017bc9, I would click install on a deb package listing, and would receive a password prompt. After furnishing the password, the package would install. The same was true of uninstalling.

On df014ea I attempt to do the same, but am met with with permissions errors:
![screenshot-2024-03-14-20-20-28_inset](https://github.com/pop-os/cosmic-store/assets/98765732/cfc428d1-13fb-4c9e-a2cd-3c98da117a44)

flatpak worked on the earlier commit and continues to work.

**Comment by jackpot51** [comment]
See if pkexec whows any dialog. If not, this is a cosmic-osd issue

**Comment by XV-02** [comment]
git bisected to 5764c9fff0205cd72aeae05c9659dec6f6f3406b for posterity.

**Comment by jackpot51** [comment]
Try 34d5750, I reenabled the interactive hint.

**Comment by jackpot51** [comment]
Improvements for deb package updates in b900bfc92a2613f404782f58bc662085dc6dab73

**Comment by XV-02** [comment]
It looks like that resolved the problem.
