### ISSUE TITLE
[Feature Request] Add equivalent to 'System Software Sources'

### ISSUE THREAD

**Issue by XV-02** [pop-os/cosmic-store#21]
With cosmic-store planned as a replacement for Pop!_Shop, it seems like an equivalent to the `System Software Sources` button, which launches Repoman, should be added to provide a method for users who aren't experience with CLI interactions to add PPAs and other system sources. 

Particularly, I look at something like Flathub's effort to verify packages origins, and how providing a GUI where those different sources can either be added, or if added can be easily white or black listed gives users more immediate and confident control of their systems.

**Comment by WatchMkr** [comment]
The plan is to include Repoman in Utilities for the initial release in Pop!_OS and develop the COSMIC repo management design for COSMIC V2 keeping in mind a good COSMIC experience across different distros and mutable and immutable systems.
