### ISSUE TITLE
[UX] Reduce right padding in cards view

### ISSUE THREAD

**Issue by git-f0x** [pop-os/cosmic-store#22]
Since the window will rarely be perfectly sized for even padding on both sides, the padding on the right should be reduced to something like `space_s` to avoid situations like this:
![screenshot-2024-03-21-17-55-58](https://github.com/pop-os/cosmic-store/assets/150025636/05d7fcb9-1d4a-48d5-b48f-814319de5685)
The cards can obviously fit in the blank area, but the padding on the right prevents them.
I tried to do this, but I only managed to reduce padding on both sides, instead of just the right.

**Comment by imbev** [comment]
I noticed the same. When Cosmic Store is only at half-width, a single column is shown and there is a lot of wasted space.
