### ISSUE TITLE
Feature Request: Update all

### ISSUE THREAD

**Issue by leb-kuchen** [pop-os/cosmic-store#31]

**Comment by leb-kuchen** [comment]
This will update all system packages, but not flatpaks and other packages.

**Comment by git-f0x** [comment]
Regarding the screenshot above, it would also be nice if that Uninstall button is removed for System Packages, since the call of the void is quite present there.

**Comment by jackpot51** [comment]
Heh I have no idea what Uninstall would do there but certainly nothing good.

**Comment by jackpot51** [comment]
@git-f0x removed the Uninstall button from the System Packages page in 736b070

**Comment by jackpot51** [comment]
I'll work on an Update All button soon.
