### ISSUE TITLE
System level flatpaks are not shown in "installed" (Fedora, all dependencies installed)

### ISSUE THREAD

**Issue by ryanabx** [pop-os/cosmic-store#37]
![screenshot-2024-04-17-16-00-57](https://github.com/pop-os/cosmic-store/assets/56272643/d38e5543-ac9a-4906-aa10-fadbefe9ac8e)

Fedora doesn't have any information on installed system-level flatpaks.

**Comment by mmstick** [comment]
Do you have packagekit packages installed?

**Comment by ryanabx** [comment]
I think I'm just missing the PackageKit package in the rpm spec, so I'll reopen this if that wasn't it.

**Comment by flukejones** [comment]
@ryanabx I'm still building from source for the moment, what was the cause of missing flatpak?

**Comment by ryanabx** [comment]
Turns out requiring PackageKit doesn't work, and I was told on the discord that appstream is what Fedora uses, so cosmic-store might have issues with appstream idk. I never got it working on my end either, so reopening this issue

**Comment by mmstick** [comment]
The store itself is appstream-based. Same as flatpak.

**Comment by flukejones** [comment]
The key part is:
```
[2024-04-19T22:15:04Z ERROR cosmic_store] failed to list installed: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
[2024-04-19T22:15:04Z ERROR cosmic_store] failed to list updates: org.freedesktop.DBus.Error.ServiceUnknown: The name is not activatable
```

Not sure which name here.

**Comment by flukejones** [comment]
I can't find `org.freedesktop.PackageKit` on my system session, only user session. I see that the backend is using a system session for it.

**Comment by mmstick** [comment]
Do you have `org.freedesktop.Packagekit` running on the system?

**Comment by flukejones** [comment]
@mmstick only in the user session. Not system session.

**Comment by flukejones** [comment]
Out of curiosity I changed the backend to use user-session and got:
```
[2024-04-19T22:28:31Z ERROR cosmic_store] failed to list installed: org.freedesktop.DBus.Error.UnknownMethod: No such interface “org.freedesktop.PackageKit” on object at path /org/freedesktop/PackageKit
```

![screenshot-2024-04-19-22-33-14](https://github.com/pop-os/cosmic-store/assets/2015870/80a960e9-1539-440e-a83b-49f539590945)

**Comment by flukejones** [comment]
@ryanabx missing the actual PackageKit rpm `dnf install PackageKit`

**Comment by flukejones** [comment]
I don't think it is showing or fetching flatpak info however.

**Comment by ryanabx** [comment]
> @ryanabx missing the actual PackageKit rpm `dnf install PackageKit`

I have it as a required dependency on my packages, didn't make a difference unfortunately :|

**Comment by ryanabx** [comment]
Update: PackageKit makes the rpms show up for base Fedora, but not the atomic variants (i.e. Silverblue, etc.). Probably not a downstream issue though.

Still missing flatpaks, and also flatpak apps don't show up in search (I've had to install flatpaks using the terminal)

**Comment by gageberz** [comment]
I don't believe PackageKit has integration with  rpm-ostree, It needs to be handled as its own plugin to the store.

**Comment by maciekk64** [comment]
I think flatpaks from system remotes aren't shown. When I added flathub-beta as a user remote (`flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`) apps are shown, but when I add it without the `--user` flag they aren't.

Also, after adding the remote I had to search something in the flatpak cli before apps would show up in the store, so something probably isn't being reloaded.

**Comment by ryanabx** [comment]
> I think flatpaks from system remotes aren't shown. When I added flathub-beta as a user remote (`flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`) apps are shown, but when I add it without the `--user` flag they aren't.
> 
> Also, after adding the remote I had to search something in the flatpak cli before apps would show up in the store, so something probably isn't being reloaded.

Adding to this, maybe it's possible that the reason flatpaks aren't shown as installed on my system is because they're all system-level flatpaks.

**Comment by flukejones** [comment]
@ryanabx you ever fully solve this?

**Comment by ryanabx** [comment]
@flukejones nope :(

**Comment by jackpot51** [comment]
> > > I think flatpaks from system remotes aren't shown. When I added flathub-beta as a user remote (`flatpak remote-add --user flathub-beta https://flathub.org/beta-repo/flathub-beta.flatpakrepo`) apps are shown, but when I add it without the `--user` flag they aren't.
> > > Also, after adding the remote I had to search something in the flatpak cli before apps would show up in the store, so something probably isn't being reloaded.
> > 
> > 
> > Adding to this, maybe it's possible that the reason flatpaks aren't shown as installed on my system is because they're all system-level flatpaks.
> 
> Yeah, unfortunately the app doesn't support them yet, see comment here: https://github.com/pop-os/cosmic-store/blob/master/src/backend/flatpak.rs#L23.
> 
> Right now in my [Bazzite fork](https://github.com/sungsphinx/bazzite), I have to work around this by using a [systemd service](https://github.com/sungsphinx/bazzite/blob/test-cosmic/system_files/desktop/cosmic/usr/lib/systemd/user/bazzite-cosmic-flatpak-manager.service) to reinstall all system-level Flatpaks as user-level ones, and it isn't really a proper solution (it also shows a polkit popup when it is removing the system-level Flathub remote and I can't find a way to stop it, even with polkit rules). Even though I prefer installing Flatpaks as the user, I think the better option would be supporting both user and system-level Flatpaks imo since most distros shipping Flatpak out of the box use system-level remotes and Flatpaks.

That honestly looks like more work than adding support for system installs to the flatpak backend.
