### ISSUE TITLE
Only Telegram deb showing where there should also be flatpak option/result

### ISSUE THREAD

**Issue by ragardner** [pop-os/cosmic-store#38]
Hello,

Sorry, I am not sure if this is due to be addressed but basically Telegram should have both a deb and a flatpak option or search result but there is only a deb,

Kind regards

In the pop!_shop:

![image](https://github.com/pop-os/cosmic-store/assets/26602401/b8b67754-b8ab-4dc8-ac96-23a1b2c11ea0)
![image](https://github.com/pop-os/cosmic-store/assets/26602401/c704d7cf-c1fa-4668-b93d-4c06c83b751a)

Cosmic-store:

![image](https://github.com/pop-os/cosmic-store/assets/26602401/53db0763-2bfc-446f-959e-9d018ee93493)
![image](https://github.com/pop-os/cosmic-store/assets/26602401/c071924a-6be7-4fc4-9355-7f13dd4cdd1d)

**Comment by git-f0x** [comment]
It shows both on my end, but you seem to be using an older version (recent commits added an Explore page on the side bar).
It will get updated in the repos soon enough, but if you don't want to wait, you can use `sudo apt-manage add popdev:master` (but note that you might get less tested packages this way).
