### ISSUE TITLE
GPU memory leak

### ISSUE THREAD

**Issue by nonetrix** [pop-os/cosmic-store#43]
## Description:

The GPU will leak GPU memory if you scroll up and down repeatedly on of the categories such as `Game`, `Create`, `Develop`, etc. I am assuming it's forgetting to deallocate GPU memory for the app icons somehow, could even be a iced toolkit issue not sure exactly. If this is fixed could possibly lead to the app being faster too I imagine

## How to reproduce:
1. Open Cosmic Store
2. Go to any of the categories or use the one already selected OTB
3. Grab the scroll bar
4. Throw your mouse up and down to scroll... P.s. Please add page up and page down support and smooth scrolling setting
5. Open a process monitor that allows you to see VRAM allocation e.g. Mission Center
6. See crazy VRAM usage and that it goes up with every scroll

## Images:
![screenshot-2024-04-23-23-36-17](https://github.com/pop-os/cosmic-store/assets/45698918/87f74f11-db0f-4658-9b78-60e0019f5919)
![screenshot-2024-04-23-23-46-44](https://github.com/pop-os/cosmic-store/assets/45698918/6f4da21a-7f7b-4479-b012-4d0b9ab2b756)

## System info:
- RX 6800 (16GBs VRAM)
- Ryzen 7 3700x
- 64GBs of RAM
- PopOS 22.04 with PPA installed

**Comment by nonetrix** [comment]
I feel like this should be fixed before a final release

**Comment by nonetrix** [comment]
Still a issue with the alpha iso

**Comment by mmstick** [comment]
We're working on rebasing to the latest version of iced. We're still using the same version from six months ago.

**Comment by git-f0x** [comment]
This appears to be fixed after the rebase!
