### ISSUE TITLE
COSMIC Store is empty (on Fedora)

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-store#61]
![screenshot-2024-05-06-16-59-00](https://github.com/pop-os/cosmic-store/assets/103491514/039690a5-e502-44a6-bd6f-fad565d2d8a8)

**Comment by mmstick** [comment]
Make sure you have packagekit and libflatpak dependencies installed.

**Comment by onlyreportingissues** [comment]
> packagekit

Have both installed, no idea what else could be missing.

**Comment by onlyreportingissues** [comment]
Works now after updating from Fedora 39 to 40.
