### ISSUE TITLE
Pop shop shows updates available but cosmic store does not

### ISSUE THREAD

**Issue by ragardner** [pop-os/cosmic-store#75]
I think these are updates related to installed flatpaks, I have kolourpaint installed as a flatpak for example,

I installed cosmic store after finding it in the pop shop

![image](https://github.com/pop-os/cosmic-store/assets/26602401/9c299805-3366-420d-aef2-53fa9f4052a6)

**Comment by jackpot51** [comment]
Correct, we aren't showing runtime updates. I will look into this soon.
