### ISSUE TITLE
Maybe missing dependency for cosmic-icons

### ISSUE THREAD

**Issue by DW8Reaper** [pop-os/cosmic-store#78]
After installing cosmic-store some icons (specifically the < icon on the Back button once you open something) do not render:
![Screenshot from 2024-05-20 10-28-23](https://github.com/pop-os/cosmic-store/assets/3433459/c7c28ed8-c013-41af-aec9-9c565824c128)

This was an easy fix I just `sudo apt install cosmic-icons` but I would expect that the dependencies would have been auto-installed, here it is after installing the icons:
![Screenshot from 2024-05-20 10-28-43](https://github.com/pop-os/cosmic-store/assets/3433459/2dd31829-502a-4746-be7f-f7c4609c0d85)

My platform is regular Pop!_OS 22.04 LTS

**Comment by mmstick** [comment]
It does have it as a dependency, but the package may not be in the release repository yet.
https://github.com/pop-os/cosmic-store/blob/master/debian/control#L24
