### ISSUE TITLE
Search works in the background when on an application's page

### ISSUE THREAD

**Issue by leviport** [pop-os/cosmic-store#79]
To recreate:
- Search for an app
- Click on a search result to view the app's page
- Click back on the search box, enter a new search term, and hit Enter

The view will remain on the app page, but clicking "Back" takes me to the search results for the term I most recently searched for.

I'm not sure what the flow is supposed to be here, but I'm thinking the second search should back me out of the individual application page I'm on and show me the search results for the new search. Conversely, we could do what Pop Shop does and make the search box insensitive while on an individual app's page, but that has always felt a bit unnatural to me, for reasons I probably can't explain well.

**Comment by WatchMkr** [comment]
> I'm thinking the second search should back me out of the individual application page I'm on and show me the search results for the new search

Yep
