### ISSUE TITLE
Add firmware update support

### ISSUE THREAD

**Issue by sylviekai** [pop-os/cosmic-store#80]
The non-Cosmic PopOS store handles firmware updates as I understand it, so filing this request under cosmic-store unless as part of the Cosmic project there are plans to put the feature elsewhere like cosmic-settings.

**Problem:** Currently when Cosmic detects a firmware upgrade it shows a notification with a prompt to click to update. Currently clicking that prompt does nothing

**Suggestion:** Add firmware support to cosmic-store to handle firmware updates and update the notification to have an onclick to pull up cosmic-store and the section for firmware updates. Maybe update the onclick to dismiss the notification and inform user firmware upgrades aren't supported yet if this feature isn't planned for alpha to prevent confusion.

Example of current notification:
![firmware](https://github.com/pop-os/cosmic-store/assets/165470978/e8fa5626-2bf8-4b6f-8f73-603d543fa75d)

**Comment by WatchMkr** [comment]
Firmware updates will be handled in COSMIC Settings.
