### ISSUE TITLE
[Feature Request] Managing system & Flatpak repositories with cosmic-store

### ISSUE THREAD

**Issue by onlyreportingissues** [pop-os/cosmic-store#82]
What I mean is having the option to enable / disable repositories from the cosmic-store settings.

**Comment by senntore** [comment]
This would be great for the final release. We have repoman right now, but it's a gtk application which I image won't be shipped as it is in the next version of Pop OS.

**Comment by leviport** [comment]
This is a duplicate of https://github.com/pop-os/cosmic-store/issues/21

Repoman will be included
