### ISSUE TITLE
[Request] Don't always automatically refresh package lists when switching to "Updates" section

### ISSUE THREAD

**Issue by jivanpal** [pop-os/cosmic-store#98]
Currently, when switching from one section of the app to the Updates section, rather than showing the current output of `apt list -u` based on the current state of the local cached package lists, Cosmic Store forcibly runs `apt update` and shows "Checking for updates...", despite this action likely not being needed. It would be better if some cache time-to-live is respected, e.g. if the package lists haven't been refreshed within the last 1 hour then do so automatically; and/or if the UI had a button to manually refresh the package lists, labelled e.g. "Check for updates" with a refresh/reload arrow icon.

**Comment by WatchMkr** [comment]
This is by design and I believe the correct descision. The reason we check updates each time is that we presume users go to the Updates page to know if there are updates regardless of the time that has passed.
